name: .NET Packaging

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}

    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build -o pub

    - name: Upload artifact
      run: dotnet nuget push pub/*.nupkg --source https://nuget.pkg.github.com/xafero/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
